
  - description: null
    label: "Clippings"
    name: "clippings"
    sort: 1
    listed: true
    hasRoute: false
    showAsTable: false
    parent: null
    content: "/content/clippings.yaml"
    fields:
      - name: "site_name"
        label: "Site Name"
        description: null
        datatype: "text"
        sort: 1
        required: true
        relationship: null
        settings:
          options: {}
      - name: "logo"
        label: "Site Logo"
        description: null
        datatype: "images"
        sort: 2
        required: null
        relationship: null
        settings:
          limit: 1
          options: {}
      - name: "footer_text"
        label: "Footer Text"
        description: null
        datatype: "text"
        sort: 3
        required: null
        relationship: null
        settings:
          options: {}
  - description: null
    label: "Dashboard Widgets"
    name: "widgets"
    sort: 1
    listed: true
    hasRoute: false
    showAsTable: false
    parent: null
    content: "/content/widgets.yaml"
    fields:
      - name: "type"
        label: "Type"
        description: null
        datatype: "text"
        sort: 10000
        required: null
        relationship: null
        settings:
          options: {}
      - name: "set_zuid"
        label: "Set ZUID"
        description: null
        datatype: "text"
        sort: 10000
        required: null
        relationship: null
        settings:
          options: {}
      - name: "direction"
        label: "Direction"
        description: null
        datatype: "text"
        sort: 10000
        required: null
        relationship: null
        settings:
          options: {}
      - name: "widget_size"
        label: "Widget Size"
        description: null
        datatype: "text"
        sort: 10000
        required: null
        relationship: null
        settings:
          options: {}
      - name: "position"
        label: "Position"
        description: null
        datatype: "number"
        sort: 10000
        required: null
        relationship: null
        settings:
          options: {}
      - name: "header"
        label: "Header"
        description: null
        datatype: "text"
        sort: 10000
        required: null
        relationship: null
        settings:
          list: 1
          options: {}
      - name: "data"
        label: "Data"
        description: null
        datatype: "textarea"
        sort: 10000
        required: null
        relationship: null
        settings:
          list: 1
          options: {}
  - description: null
    label: "Homepage"
    name: "homepage"
    sort: 1
    listed: true
    hasRoute: true
    showAsTable: false
    parent: null
    view: "/views/homepage.tpl"
    content: "/content/homepage.yaml"
    fields:
      - name: "title"
        label: "Title"
        description: null
        datatype: "text"
        sort: 1
        required: true
        relationship: null
        settings:
          options: {}
      - name: "content"
        label: "Intro Text"
        description: null
        datatype: "wysiwyg_advanced"
        sort: 2
        required: null
        relationship: null
        settings:
          options: {}
      - name: "image"
        label: "Main Image"
        description: null
        datatype: "images"
        sort: 3
        required: null
        relationship: null
        settings:
          limit: 1
          options: {}
  - description: "Example content model to display Layouts"
    label: "Layouts"
    name: "layouts"
    sort: 100
    listed: true
    hasRoute: true
    showAsTable: false
    parent: null
    view: "/views/layouts.tpl"
    content: "/content/layouts.yaml"
    fields:
      - name: "title"
        label: "Title"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "rich_text"
        label: "Rich Text"
        description: ""
        datatype: "wysiwyg_basic"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "image"
        label: "Image"
        description: ""
        datatype: "images"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "image_wide"
        label: "Image (wide)"
        description: ""
        datatype: "images"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "external_url"
        label: "External URL"
        description: ""
        datatype: "link"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
  - description: ""
    label: "A/B"
    name: "a_b_example"
    sort: 102
    listed: true
    hasRoute: true
    showAsTable: false
    parent: null
    view: "/views/a_b_example.tpl"
    content: "/content/a_b_example.yaml"
    fields:
      - name: "title"
        label: "Title"
        description: ""
        datatype: "text"
        sort: 1
        required: false
        relationship: null
        settings:
          list: true
      - name: "content"
        label: "Content"
        description: ""
        datatype: "wysiwyg_basic"
        sort: 2
        required: false
        relationship: null
        settings:
          list: true
      - name: "image"
        label: "Image"
        description: ""
        datatype: "images"
        sort: 3
        required: false
        relationship: null
        settings:
          list: true
      - name: "ab_options"
        label: "AB options"
        description: ""
        datatype: "one_to_many"
        sort: 0
        required: false
        relationship:
          name: "a_b_options"
          display: "utm_campaign"
        settings:
          list: true
      - name: "zesty_documentation"
        label: "Zesty Documentation"
        description: ""
        datatype: "wysiwyg_basic"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
  - description: ""
    label: "A/B Options"
    name: "a_b_options"
    sort: 104
    listed: true
    hasRoute: false
    showAsTable: false
    parent: "a_b_example"
    content: "/content/a_b_options.yaml"
    fields:
      - name: "title"
        label: "Title"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "content"
        label: "Content"
        description: ""
        datatype: "wysiwyg_basic"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "image"
        label: "Image"
        description: ""
        datatype: "images"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "utm_campaign"
        label: "UTM Campaign"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
  - description: ""
    label: "Personalization"
    name: "personalization"
    sort: 108
    listed: true
    hasRoute: true
    showAsTable: false
    parent: null
    view: "/views/personalization.tpl"
    content: "/content/personalization.yaml"
    fields:
      - name: "title"
        label: "Title"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "description"
        label: "Description"
        description: ""
        datatype: "wysiwyg_basic"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "image"
        label: "image"
        description: ""
        datatype: "images"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "zesty_documentation"
        label: "Zesty Documentation"
        description: ""
        datatype: "wysiwyg_basic"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "personas_to_display"
        label: "Personas to Display"
        description: ""
        datatype: "one_to_many"
        sort: 10000
        required: false
        relationship:
          name: "personas"
          display: "name"
        settings:
          list: true
  - description: ""
    label: "Personas"
    name: "personas"
    sort: 110
    listed: true
    hasRoute: false
    showAsTable: false
    parent: null
    content: "/content/personas.yaml"
    fields:
      - name: "name"
        label: "Name"
        description: ""
        datatype: "text"
        sort: 1
        required: false
        relationship: null
        settings:
          list: true
      - name: "default_avatar"
        label: "Default Avatar"
        description: ""
        datatype: "images"
        sort: 0
        required: false
        relationship: null
        settings:
          list: true
  - description: ""
    label: "Articles"
    name: "articles"
    sort: 111
    listed: true
    hasRoute: true
    showAsTable: true
    parent: null
    view: "/views/articles.tpl"
    content: "/content/articles.yaml"
    fields:
      - name: "title"
        label: "Title"
        description: ""
        datatype: "text"
        sort: 0
        required: false
        relationship: null
        settings:
          list: true
      - name: "content"
        label: "Content"
        description: ""
        datatype: "wysiwyg_basic"
        sort: 3
        required: false
        relationship: null
        settings:
          list: true
      - name: "targeted_personas"
        label: "Targeted Personas"
        description: ""
        datatype: "one_to_many"
        sort: 2
        required: false
        relationship:
          name: "personas"
          display: "name"
        settings:
          list: true
      - name: "image"
        label: "image"
        description: ""
        datatype: "images"
        sort: 1
        required: false
        relationship: null
        settings:
          list: true
